---
AWSTemplateFormatVersion: 2010-09-09
Description: Setup Resources
Parameters:
  vpcdefault:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
    Default: vpc-e05eae8b

Resources:
  MyInstances:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-08df646e18b182346
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref ServerSecurityGroup

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Controls connection
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: ''
          ToPort: ''
          CidrIp: 0.0.0.0/0
      VpcId: !Ref vpcdefault